### ISSUE TITLE
Define all feedback types for TypeScript

### ISSUE THREAD

**Issue by krszwsk** [AppAndFlow/react-native-haptic#14]
Currently there are only 3 types defined in the ts definition.

**Comment by krszwsk** [comment]
It would also be useful to export a HapticFeedbackType from the module (eg. for wrappers, higher-order components).

**Comment by krszwsk** [comment]
I can look into this later today.

**Comment by charlesvinette** [comment]
Thanks @krszwsk !

**Comment by krszwsk** [comment]
@charlesvinette I opened a pull request earlier today, take a look if you have a minute and let me know if it's okay.
