### ISSUE TITLE
Licence

### ISSUE THREAD

**Issue by jacobp100** [AppAndFlow/react-native-haptic#16]
Could you add a licence? 😀

If it's a permissive one, I was thinking about sending a PR to implement this in the RN core

**Comment by charlesvinette** [comment]
Hey Jacob! Thank you so much for your help. I submitted a PR when I first released the package but the RN Core team decided that they would prefer to have it as a package instead of including in in the Core. If you want to give it another go feel free to do so, I'll add the license soon.

Cheers!

**Comment by charlesvinette** [comment]
Done deal sir! Closing this. Thanks
