### ISSUE TITLE
More feedback types for impact and notification

### ISSUE THREAD

**Issue by jhen0409** [AppAndFlow/react-native-haptic#2]
[Feedback guideline from Apple](https://developer.apple.com/ios/human-interface-guidelines/user-interaction/feedback)

Currently this module isn't supported all feedback types for `impact` and `notification`

- `impact` - [UIImpactFeedbackStyle](https://developer.apple.com/reference/uikit/uiimpactfeedbackstyle)
- `notification` - [UINotificationFeedbackType](https://developer.apple.com/reference/uikit/uinotificationfeedbacktype)

Let me know if PR welcome. :)

**Comment by charlesvinette** [comment]
Hey @jhen0409 . Wow, I am so sorry I didn't get back to you before, I totally missed the issue. PR's are more than welcome! Cute dog by the way :)

**Comment by Spshulem** [comment]
Second this. Thank you for this, definitely helpful! 

Here is a full list of feedbacks: 

**Notifications:**
- [ ] Success
- [ ] Warning
- [ ] Failure

**Impact:**
- [ ] Light
- [ ] Medium
- [ ] Heavy

**Selection:**
- [ ] Selection

https://developer.apple.com/ios/human-interface-guidelines/user-interaction/feedback/

Look likes currently supported is:

- [ ] Warning
- [ ] Possibly light, or medium, or heavy
- [ ] Selection

**Comment by Dexwell** [comment]
Any movement on this? Would be very much appreciated 🙏🏼

**Comment by charlesvinette** [comment]
Hey @Spshulem and @Dexwell, thanks for your feedback. I will take some next week to add those. I'll get back to you then. Have a good weekend!

**Comment by Dexwell** [comment]
Don't mean to pressure you, but any ETA on this? 💝

**Comment by charlesvinette** [comment]
Hey no pressure at all, I am so sorry for the wait @Dexwell we are busy these past couple of weeks haha. I'd really like to take some time 'soonish' to add those. I will ping back when it is, hopefully by the end of the month :)

**Comment by charlesvinette** [comment]
@Dexwell Haha hey Doney, sorry about that, I was planning April 😬 but things are crazy at App & Flow so I had to postpone. It's still on my to do list. PR's welcomed !!

**Comment by bryanjclark** [comment]
Working on a PR!

**Comment by Dexwell** [comment]
@bryanjclark Music to my ears! 💜
