### ISSUE TITLE
How to make it works on iPhone 6, 6s?

### ISSUE THREAD

**Issue by 2vm** [AppAndFlow/react-native-haptic#6]
I tested this lib on iPhoneX and it works like a charm.
But on iPhone 6s it doesn't work at all.

I've figured out, that on iPhone > 7 it works with different API then on iPhone 6, 6s.
On 6, 6s we should use something like this: 
``` swift
import AudioToolbox.AudioServices

// 'Peek' feedback (weak boom)
let peek = SystemSoundID(1519)
AudioServicesPlaySystemSound(peek)
```
When in iPhone > 7 we use this:
``` swift
import UIKit

let notificationFeedbackGenerator = UINotificationFeedbackGenerator()
```
So, can you extend your library? A lot of people will be appreciated :)
Here is some info: https://medium.com/@sdrzn/make-your-ios-app-feel-better-a-comprehensive-guide-over-taptic-engine-and-haptic-feedback-724dec425f10

**Comment by charlesvinette** [comment]
Hey! Thanks for the suggestion. I will find some time soon to work on the library and I will look into this.

**Comment by ariellam** [comment]
I've submitted a pull request for this issue here:

https://github.com/AppAndFlow/react-native-haptic/pull/7

Hope this helps!

**Comment by charlesvinette** [comment]
Thanks to @ariellam , this has been merged in!

**Comment by brendan-rius** [comment]
It looks like it's working when using the master branch on Git instead of the latest NPM package.

Could you please release the new NPM package? Thanks!

**Comment by charlesvinette** [comment]
@brendan-rius Sorry about that, done deal! Published the updated package. Thanks again @ariellam
